# Generated by Django 6.0.4 on 2026-05-02 22:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSubmission',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('processing', 'En traitement OCR'), ('incomplete', 'Dossier incomplet'), ('complete', 'Dossier complet'), ('elimine', 'Éliminé'), ('evaluated', 'Évalué')], default='draft', max_length=30)),
                ('price_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prix HT (FCFA)')),
                ('price_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prix TTC (FCFA)')),
                ('execution_delay', models.PositiveIntegerField(blank=True, null=True, verbose_name='Délai (jours)')),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('elimination_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenders.tender')),
            ],
            options={
                'verbose_name': 'historical submission',
                'verbose_name_plural': 'historical submissions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('processing', 'En traitement OCR'), ('incomplete', 'Dossier incomplet'), ('complete', 'Dossier complet'), ('elimine', 'Éliminé'), ('evaluated', 'Évalué')], default='draft', max_length=30)),
                ('price_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prix HT (FCFA)')),
                ('price_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prix TTC (FCFA)')),
                ('execution_delay', models.PositiveIntegerField(blank=True, null=True, verbose_name='Délai (jours)')),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('elimination_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tenders.tender')),
            ],
            options={
                'ordering': ['-total_score', 'rank'],
                'unique_together': {('tender', 'submitter')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('attestation_fiscale', 'Attestation fiscale'), ('rccm', 'RCCM'), ('non_faillite', 'Attestation de non-faillite'), ('bilan', 'Bilan financier'), ('offre_technique', 'Offre technique'), ('offre_financiere', 'Offre financière'), ('references', 'Références similaires'), ('autres', 'Autres')], max_length=50)),
                ('file', models.FileField(upload_to='submissions/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('ocr_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='submissions.submission')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=200)),
                ('raw_value', models.TextField(blank=True)),
                ('cleaned_value', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('manually_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='submissions.submission')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.submissiondocument')),
            ],
            options={
                'unique_together': {('submission', 'field_name')},
            },
        ),
    ]
