# Generated by Django 6.0.4 on 2026-05-02 22:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTender',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('tender_type', models.CharField(choices=[('travaux', 'Travaux'), ('fournitures', 'Fournitures'), ('services', 'Services intellectuels'), ('prestations', 'Prestations de services')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('closed', 'Clôturé'), ('evaluation', 'En évaluation'), ('attributed', 'Attribué'), ('cancelled', 'Annulé')], default='draft', max_length=30)),
                ('budget_estimated', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_public', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(help_text='Date limite de soumission')),
                ('opening_date', models.DateTimeField(blank=True, null=True)),
                ('attribution_date', models.DateTimeField(blank=True, null=True)),
                ('required_documents', models.JSONField(default=list)),
                ('eliminating_documents', models.JSONField(default=list)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('winner_score', models.FloatField(blank=True, null=True)),
                ('dao_file', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.organization')),
                ('winner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical Appel d'offres",
                'verbose_name_plural': "historical Appel d'offress",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('tender_type', models.CharField(choices=[('travaux', 'Travaux'), ('fournitures', 'Fournitures'), ('services', 'Services intellectuels'), ('prestations', 'Prestations de services')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('closed', 'Clôturé'), ('evaluation', 'En évaluation'), ('attributed', 'Attribué'), ('cancelled', 'Annulé')], default='draft', max_length=30)),
                ('budget_estimated', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_public', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(help_text='Date limite de soumission')),
                ('opening_date', models.DateTimeField(blank=True, null=True)),
                ('attribution_date', models.DateTimeField(blank=True, null=True)),
                ('required_documents', models.JSONField(default=list)),
                ('eliminating_documents', models.JSONField(default=list)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('winner_score', models.FloatField(blank=True, null=True)),
                ('dao_file', models.FileField(blank=True, null=True, upload_to='dao_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tenders', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='accounts.organization')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tenders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Appel d'offres",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight', models.FloatField(help_text='Poids en pourcentage (0-100)')),
                ('evaluation_type', models.CharField(choices=[('auto_price', 'Automatique (Prix)'), ('auto_delay', 'Automatique (Délai)'), ('auto_financial', 'Automatique (Capacité financière)'), ('manual', 'Manuel (Évaluateur)')], default='manual', max_length=30)),
                ('max_score', models.FloatField(default=100)),
                ('is_eliminating', models.BooleanField(default=False)),
                ('min_threshold', models.FloatField(blank=True, help_text='Score minimum pour ne pas être éliminé', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('locked', models.BooleanField(default=False, help_text='Verrouillé après publication')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='tenders.tender')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EvaluatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_assignments', to=settings.AUTH_USER_MODEL)),
                ('criteria', models.ManyToManyField(blank=True, to='tenders.criterion')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_assignments', to='tenders.tender')),
            ],
            options={
                'unique_together': {('tender', 'evaluator')},
            },
        ),
    ]
